---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# allin1

<!-- badges: start -->
<!-- badges: end -->

The goal of `allin1` is to provide shortcuts for usually tedious functions

## Installation

You can install the development version of `allin1` from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("ADC-405-S26/allin1")
```

## Examples

This is a basic example which shows you how to solve a common problem:

```{r example}
library(allin1)
```

#### sort_mutate example

```{r}
employees |> 
  sort_mutate("earnings", hours_worked * hourly_wage, desc = TRUE)
```

#### drop_na_rows example

```{r}
clean_employees <- employees |> drop_na_rows()
clean_employees
```

#### top_n_percent example

```{r}
employees |> 
  top_n_percent(hourly_wage, percent = 50)
```

